Resources:
  # Master credentials para RDS
  DBMasterPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:custom.dbMasterPasswordSecretName}
      Description: "RDS Master user credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "${self:custom.dbMasterUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # Secretos individuales para R2DBC (para usar como variables de entorno)
  R2DBCHostSecret:
    Type: AWS::SecretsManager::Secret
    DependsOn: RDSInstance
    Properties:
      Name: ${self:service}-${self:provider.stage}-r2dbc-host
      Description: "R2DBC Host endpoint"
      SecretString: !GetAtt RDSInstance.Endpoint.Address

  R2DBCPortSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-r2dbc-port
      Description: "R2DBC Port"
      SecretString: "3306"

  R2DBCUsernameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-r2dbc-username
      Description: "R2DBC Username"
      SecretString: ${self:custom.appUsername}

  R2DBCPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-r2dbc-password
      Description: "R2DBC Password"
      SecretString: ${self:custom.appPassword}

  # JWT Secret para microservicios
  JWTSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-jwt-secret-key
      Description: "JWT secret key"
      SecretString: "bWlDbGF2ZVNlY3JldGFNdXlMYXJnYVBhcmFKV1RDb25BbE1lbm9zMzJDYXJhY3RlcmVzUGFyYVNlZ3VyaWRhZA=="

  JWTExpirationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-jwt-expiration
      Description: "JWT expiration time"
      SecretString: ${self:custom.jwtExpiration}

  # URLs de SQS como secretos individuales
  SQSNotificacionesURL:
    Type: AWS::SecretsManager::Secret
    DependsOn: EmailQueue
    Properties:
      Name: ${self:service}-${self:provider.stage}-sqs-notificaciones-url
      Description: "SQS Notificaciones Queue URL"
      SecretString: !Ref EmailQueue

  SQSCapacidadEndeudamientoURL:
    Type: AWS::SecretsManager::Secret
    DependsOn: LoanRequestQueue
    Properties:
      Name: ${self:service}-${self:provider.stage}-sqs-capacidad-endeudamiento-url
      Description: "SQS Capacidad Endeudamiento Queue URL"
      SecretString: !Ref LoanRequestQueue

  SQSNotificacionesSolicitudURL:
    Type: AWS::SecretsManager::Secret
    DependsOn: MicroserviceQueue
    Properties:
      Name: ${self:service}-${self:provider.stage}-sqs-notificaciones-solicitud-url
      Description: "SQS Notificaciones Solicitud Queue URL"
      SecretString: !Ref MicroserviceQueue

  SQSReportesURL:
    Type: AWS::SecretsManager::Secret
    DependsOn: SolicitudesReportesQueue
    Properties:
      Name: ${self:service}-${self:provider.stage}-sqs-reportes-url
      Description: "SQS Reportes Queue URL"
      SecretString: !Ref SolicitudesReportesQueue

  SQSReporteDiarioURL:
    Type: AWS::SecretsManager::Secret
    DependsOn: ReportesEmailQueue
    Properties:
      Name: ${self:service}-${self:provider.stage}-sqs-reporte-diario-url
      Description: "SQS Reporte Diario Queue URL"
      SecretString: !Ref ReportesEmailQueue

  # DynamoDB Table Name
  DynamoDBReportesTableName:
    Type: AWS::SecretsManager::Secret
    DependsOn: ReportesTable
    Properties:
      Name: ${self:service}-reportes-${self:provider.stage}
      Description: "DynamoDB Reportes Table Name"
      SecretString: !Ref ReportesTable

  # ALB DNS para comunicación interna
  ALBDNSName:
    Type: AWS::SecretsManager::Secret
    DependsOn: ApplicationLoadBalancer
    Properties:
      Name: ${self:service}-${self:provider.stage}-alb-dns
      Description: "ALB DNS Name for internal communication"
      SecretString: !GetAtt ApplicationLoadBalancer.DNSName

Outputs:
  DBMasterPasswordSecretArn:
    Description: ARN of database master password secret
    Value: !Ref DBMasterPasswordSecret
    Export:
      Name: ${self:service}-${self:provider.stage}-db-master-secret-arn

  R2DBCHostSecretArn:
    Description: ARN of R2DBC Host secret
    Value: !Ref R2DBCHostSecret
    Export:
      Name: ${self:service}-${self:provider.stage}-r2dbc-host-arn

  R2DBCUsernameSecretArn:
    Description: ARN of R2DBC Username secret
    Value: !Ref R2DBCUsernameSecret
    Export:
      Name: ${self:service}-${self:provider.stage}-r2dbc-username-arn

  JWTSecretKeyArn:
    Description: ARN of JWT secret key
    Value: !Ref JWTSecretKey
    Export:
      Name: ${self:service}-${self:provider.stage}-jwt-secret-key-arn